---
- name: Install and configure Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Configure Nginx
      template:
        src: /home/lisdemlord/Documents/project-ansible/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

    - name: Ensure Nginx is running
      systemd:
        name: nginx
        state: started

    - name: Check if Nginx is serving HTTP on port 80
      uri:
        url: http://localhost
        return_content: yes
      register: http_response

    - name: Display Nginx HTTP response
      debug:
        msg: "Nginx is serving content: {{ http_response.content | truncate(50) }}"

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

