---
- name: Run a script on remote servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Test connection
      ping:
      register: ping_result

    - name: Run the script and capture the output
      ansible.builtin.script:
        cmd: /home/lisdemlord/Documents/project-ansible/check_dependecies.sh
      environment:
        ANSIBLE_REMOTE_TEMP: /tmp/ansible-test
      register: script_output

    - name: Show the ping result
      debug:
        msg: |
          Ping result for {{ inventory_hostname }}:
            pong: {{ ping_result.ping }}
            changed: {{ ping_result.changed }}
            failed: {{ ping_result.failed }}

    - name: Show the script output
      debug:
        msg: "{{ script_output.stdout.split('\n') }}"

