---
- name: Run a script on remote servers
  hosts: webservers
  gather_facts: no
  tasks:
    - name: Test connection
      ping:
      register: ping_result

    - name: Copy script to remote servers
      copy:
        src: /home/lisdemlord/Documents/project-ansible/check_dependecies.sh
        dest: /tmp/check_dependecies.sh
        mode: '0755'

    - name: Run the script and capture the output
      shell: /tmp/check_dependecies.sh
      register: script_output

    - name: Show the ping result
      debug:
        msg: |
          Ping result for {{ inventory_hostname }}:
            pong: {{ ping_result.ping }}
            changed: {{ ping_result.changed }}
            failed: {{ ping_result.failed }}


    - name: Show the script output
      debug:
        msg: "{{ script_output.stdout.split('\n') }}"

